services:

  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ./ollama/ollama-data:/root/.ollama
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

  app:
    build: ./BE-flask
    container_name: flask-app
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./BE-flask/data:/app/data
      - ./BE-flask/templates:/app/templates
      - ./BE-flask/modules:/app/modules
      - ./BE-flask/utils:/app/utils
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

  strapi:
    build: ./BE-strapi
    container_name: strapi
    ports:
      - "0.0.0.0:1337:1337"
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
    restart: always
    networks:
      - ai-network

  frontend:
    build: ./FECapstone
    container_name: frontend
    ports:
      - "0.0.0.0:3000:80"
    restart: always
    networks:
      - ai-network

  wa-js:
    build: ./wa-bot
    container_name: wa-js
    ports:
      - "0.0.0.0:5001:5001"
    restart: always
    networks:
      - ai-network

networks:
  ai-network:
    external: true
