services:
  strapi:
    build: ./BE-strapi
    container_name: strapi
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
    restart: unless-stopped
    networks:
      - ai-network

  frontend:
    build: ./FECapstone
    container_name: frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - ai-network

  app:
    build: ./BE-flask
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./BE-flask/data:/app/data
      - ./BE-flask/templates:/app/templates
      - ./BE-flask/modules:/app/modules
      - ./BE-flask/utils:/app/utils
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  wa-flask:
    build: ./wa-bot/wa-flask
    container_name: wa-flask
    ports:
      - "5001:5001"
    volumes:
      - ./wa-bot/wa-flask:/app
    restart: always
    networks:
      - ai-network

  wa-js:
    build: ./wa-bot/wa-js
    container_name: wa-js
    volumes:
      - ./wa-bot/wa-js:/app
    restart: always
    networks:
      - ai-network

# Ketika sudah fix uncomment gunakan yang /ollama
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama-data:/root/.ollama
  #     - ./ollama/entrypoint.sh:/app/entrypoint.sh
  #   networks:
  #     - ai-network
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #   restart: unless-stopped
  #   entrypoint: /app/entrypoint.sh

networks:
  ai-network:
    external: true
