services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./modules:/app/modules
    environment:
      - STRAPI_URL=http://strapi:1337 # Added Strapi URL
      - OLLAMA_HOST=http://ollama:11434 # Assuming ollama is on the same network
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

networks:
  ai-network:
    driver: bridge
