services:
  chatbot:
    build: ./ai
    container_name: chatbot
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL=phi4:14b
    volumes:
      - ./ai/templates:/app/templates
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
