services:
  strapi:
    build: .
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
      - ./src:/app/src
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/data.db
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
