services:
  strapi:
    build: .
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./src:/app/src
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: sqlite
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    external: true
