services:
  chatbot:
    build: ./ai
    container_name: chatbot
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Gunakan nama container Ollama
      - MODEL=deepseek-r1:7b
    volumes:
      - ./ai/behaviour:/app/behaviour
      - ./ai/knowledge:/app/knowledge
      - ./ai/templates:/app/templates
    networks:
      - ai-network
    restart: unless-stopped

networks:
  ai-network:
    external: true
