version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - FLASK_DEBUG=1
      - ENVIRONMENT=development
    volumes:
      - ./:/app
      - ./data/markdown:/app/markdown
      - ./data/chroma:/app/chroma
      - ./data/original:/app/original
      - ./logs:/app/logs
    networks:
      - ai-network
    depends_on:
      ollama:
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  ai-network:
    driver: bridge