version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=ollama
    volumes:
      - ./data/markdown:/app/markdown
      - ./data/chroma:/app/chroma
      - ./data/original:/app/original
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

networks:
  ai-network:
    driver: bridge